//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jotun.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jotunDBEntities : DbContext
    {
        public jotunDBEntities()
            : base("name=jotunDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tblAppointment> tblAppointments { get; set; }
        public virtual DbSet<tblAttribute> tblAttributes { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCategoryAttribute> tblCategoryAttributes { get; set; }
        public virtual DbSet<tblCustomer_location> tblCustomer_location { get; set; }
        public virtual DbSet<tblCustomerPointHistory> tblCustomerPointHistories { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblCustomerType> tblCustomerTypes { get; set; }
        public virtual DbSet<tblInvoice> tblInvoices { get; set; }
        public virtual DbSet<tblJeweler> tblJewelers { get; set; }
        public virtual DbSet<tblProductAttribute> tblProductAttributes { get; set; }
        public virtual DbSet<tblProductByUnit> tblProductByUnits { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblPurchaseBySupplier> tblPurchaseBySuppliers { get; set; }
        public virtual DbSet<tblPurchaseBySupplierDetail> tblPurchaseBySupplierDetails { get; set; }
        public virtual DbSet<tblSaleLabour> tblSaleLabours { get; set; }
        public virtual DbSet<tblSaleLabourDetail> tblSaleLabourDetails { get; set; }
        public virtual DbSet<tblSale> tblSales { get; set; }
        public virtual DbSet<tblSalesDetail> tblSalesDetails { get; set; }
        public virtual DbSet<tblService> tblServices { get; set; }
        public virtual DbSet<tblServiceBooked> tblServiceBookeds { get; set; }
        public virtual DbSet<tblServiceProduct> tblServiceProducts { get; set; }
        public virtual DbSet<tblServiceProvided> tblServiceProvideds { get; set; }
        public virtual DbSet<tblServiceType> tblServiceTypes { get; set; }
        public virtual DbSet<tblShipper> tblShippers { get; set; }
        public virtual DbSet<tblStaff> tblStaffs { get; set; }
        public virtual DbSet<tblSupplier> tblSuppliers { get; set; }
        public virtual DbSet<tblTable> tblTables { get; set; }
        public virtual DbSet<tblUnit> tblUnits { get; set; }
        public virtual DbSet<tbSalePayment> tbSalePayments { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<PackageProduct> PackageProducts { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PackageService> PackageServices { get; set; }
        public virtual DbSet<tb_Acc_Account> tb_Acc_Account { get; set; }
        public virtual DbSet<tb_Acc_AccountType> tb_Acc_AccountType { get; set; }
        public virtual DbSet<tb_Acc_Expense> tb_Acc_Expense { get; set; }
        public virtual DbSet<tb_Acc_Expense_Detail> tb_Acc_Expense_Detail { get; set; }
        public virtual DbSet<tb_Expense_Amount> tb_Expense_Amount { get; set; }
        public virtual DbSet<tb_Expense_Topup> tb_Expense_Topup { get; set; }
        public virtual DbSet<tblExchangeRate> tblExchangeRates { get; set; }
        public virtual DbSet<tblModule> tblModules { get; set; }
        public virtual DbSet<tblShop> tblShops { get; set; }
        public virtual DbSet<tblShopModulePermission> tblShopModulePermissions { get; set; }
    }
}
