//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jotun.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageProduct
    {
        public int PackageId { get; set; }
        public string ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
