//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jotun.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Acc_Expense_Detail
    {
        public int Id { get; set; }
        public Nullable<int> ExpenseId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string Reason { get; set; }
        public string SuppplierName { get; set; }
        public string SupplierContact { get; set; }
        public Nullable<int> RefId { get; set; }
    }
}
