//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jotun.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Expense_Amount
    {
        public int Id { get; set; }
        public Nullable<decimal> TotalTopupAmount { get; set; }
        public Nullable<decimal> RemainTopupAmount { get; set; }
        public Nullable<decimal> TotalExpense { get; set; }
        public Nullable<int> ShopId { get; set; }
    }
}
