//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jotun.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerPointHistory
    {
        public int SalePointHistoryId { get; set; }
        public string SaleId { get; set; }
        public string CustomerId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> PointQTY { get; set; }
        public Nullable<decimal> PointAmount { get; set; }
    }
}
