//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jotun.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalary
    {
        public int SalaryId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> BaseSalary { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<System.DateTime> SalaryDate { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
