//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jotun.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceProvided
    {
        public string Id { get; set; }
        public string AppointmentId { get; set; }
        public string ServiceId { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
