//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jotun.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleLabour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSaleLabour()
        {
            this.tblSaleLabourDetails = new HashSet<tblSaleLabourDetail>();
        }
    
        public long Id { get; set; }
        public string CustomerId { get; set; }
        public string JewelerId { get; set; }
        public string Category { get; set; }
        public string Color { get; set; }
        public string Weight { get; set; }
        public string FinishWeight { get; set; }
        public string LabourCost { get; set; }
        public string LabourDesignCost { get; set; }
        public string Length { get; set; }
        public string Size { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string ImagePath { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblJeweler tblJeweler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleLabourDetail> tblSaleLabourDetails { get; set; }
    }
}
