//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppointmentDate.
        /// </summary>
        internal static string AppointmentDate {
            get {
                return ResourceManager.GetString("AppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment List.
        /// </summary>
        internal static string AppointmentList {
            get {
                return ResourceManager.GetString("AppointmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppointmentStatus.
        /// </summary>
        internal static string AppointmentStatus {
            get {
                return ResourceManager.GetString("AppointmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerContact.
        /// </summary>
        internal static string CustomerContact {
            get {
                return ResourceManager.GetString("CustomerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerName.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available in table.
        /// </summary>
        internal static string datatableEmptyTable {
            get {
                return ResourceManager.GetString("datatableEmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ entries.
        /// </summary>
        internal static string datatableInfo {
            get {
                return ResourceManager.GetString("datatableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing 0 to 0 of 0 entries.
        /// </summary>
        internal static string datatableInfoEmpty {
            get {
                return ResourceManager.GetString("datatableInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _MENU_ entries.
        /// </summary>
        internal static string datatableLengthMenu {
            get {
                return ResourceManager.GetString("datatableLengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string datatableNext {
            get {
                return ResourceManager.GetString("datatableNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string datatablePrevious {
            get {
                return ResourceManager.GetString("datatablePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string datatableSearch {
            get {
                return ResourceManager.GetString("datatableSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        internal static string datatableZeroRecords {
            get {
                return ResourceManager.GetString("datatableZeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string detailData {
            get {
                return ResourceManager.GetString("detailData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeName.
        /// </summary>
        internal static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndTime.
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string invoicePrint {
            get {
                return ResourceManager.GetString("invoicePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceFinal.
        /// </summary>
        internal static string PriceFinal {
            get {
                return ResourceManager.GetString("PriceFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTime.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
    }
}
